apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: test123
spec:
  project: ns.test123.scratch0.sandbox0
  source:
    repoURL: https://github.com/Azulinho/miniature-octo-funicular.git
    path: sandbox0/scratch0/test123/nginx-ingress-controller/
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: false
