apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: infra
  version: "112"
spec:
  project: infra.on.scratch0
  source:
    repoURL: https://github.com/Azulinho/miniature-octo-funicular.git
    path: sandbox0/scratch0/infra/nginx-ingress-controller/manifests
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: false
