apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpmyadmin
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra.on.scratch0
  source:
    helm:
      valueFiles:
      - values.yaml
    path: charts/bitnami/phpmyadmin
    repoURL: https://github.com/bitnami/charts.git
    targetRevision: master
    valuesFiles:
    - values.yaml
  syncPolicy:
    automated:
      prune: true
