apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpmyadmin
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra.on.scratch0
  source:
    helm:
      parameters:
        - name: "service.type"
          value: "ClusterIP"
    path: charts/bitnami/phpmyadmin
    repoURL: https://github.com/bitnami/charts.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
