apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
spec:
  destination:
    name: ''
    namespace: infra
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 3.23.0
    chart: ingress-nginx
    helm:
      parameters:
        - name: controller.setAsDefaultIngress
          value: "true"
  project: infrastructure.on.scratch0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

