---
# Source: ingress-nginx/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: ingress-nginx-3.23.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx-controller
    app.kubernetes.io/version: "0.44.0"
    app.kubernetes.io/managed-by: Helm
  name: ingress-nginx-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-controller
subjects:
  - kind: ServiceAccount
    name: ingress-nginx-controller
    namespace: "default"
